version: 2.1
orbs:
  node: circleci/node@5.0.3
  aws-cli: circleci/aws-cli@3.1.4
jobs:
  build: # name of your job
    docker: # executor type
      - image: cimg/base:stable # primary container will run the latest, production-ready base image
    working_directory: ~/udagram
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
# Backend commands (install, build and deploy)
      - run:
          name: Backend-End Install
          command: |
            npm run api:install
      - run:
          name: Backend-End Build
          command: |
            npm run api:build
      - run:
          name: Backend-End Deploy
          command: |
            npm run api:deploy
workflows:
  frontend_and_backend:
    jobs:
      - build

# VS Code Extension Version: 1.3.0