branch-defaults:
  default:
    environment: Server-env
    group_suffix: null
deploy:
  artifact: www/Archive.zip
environment-defaults:
  Server-env:
    branch: null
    repository: null
  Udagram-env:
    branch: null
    repository: null
  udagram-server-env:
    branch: null
    repository: null
global:
  application_name: server
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
